import 'dart:core';
import 'dart:math';
import 'dart:convert';
import 'cache_store.dart';
import 'base64url.dart';

/// CacheSession factory
///
/// Class in charge of managing the active
/// Cache Sessions generated by the application
class CacheSession {
  final String sessionId;
  final CacheStore cache = CacheStore();  

  /// factory: cache a new CacheSession object
  /// instance in a Map.
  static final Map<String, CacheSession> _sessions = <String, CacheSession>{};
 
  /// factory: creates a new CacheSession object
  /// if it is not present in the CacheSession
  /// cache
  factory CacheSession(String id) {
    return _sessions.putIfAbsent(id, () {
      return CacheSession._init(id);
    });
  }

  /// constructor used to initialized the session Idy
  CacheSession._init(this.sessionId);

  /// factory: checks if a specific session id is already
  /// present in cache.
  static bool exists(String id) {
    return _sessions.containsKey(id);
  }

  /// factory: removes a session in cache using
  /// its session id
  static String? delete(String sessionId) {
    if (_sessions.remove(sessionId) != null) {
      return sessionId;
    }
    return null;
  }

  /// boilerplate to convert the session Id to string
  String toString() => sessionId;
}

/// check if a session id is valid
bool checkSessionId(String sessionId) {
  if (sessionId.length>32) {
    return false;
  }
  RegExp regexp = RegExp(r'^([a-zA-Z0-9_-])+$');
  if (regexp.firstMatch(sessionId) == null) {
    return false;
  }
  return true;
}

/// generate a random session id
String generateSessionId(int length) {
  List<int> buf = [];
  final r = Random.secure();
  for (;length>0;length--)
    buf.add(r.nextInt(1<<8));
  return base64url(buf);
}

/// quick and dirty base64url implementation
///
/// Returns a base64url string by converting
/// a base64 to base64url format ('+' replaced
/// by '-' and '/' replaced by '_'). This is
/// dirty as hell, but it should work.
String base64url(List<int> list) {
  String b64 = base64.encode(list);
  return toBase64Url(b64);
}
